# Generated by Django 3.0.8 on 2020-08-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmModel',
        ),
    ]
