# Generated by Django 3.0.8 on 2020-08-28 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0002_delete_firmmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Модель')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.Firm', verbose_name='Фирма')),
            ],
            options={
                'verbose_name': 'Фирма',
                'verbose_name_plural': 'Фирмы',
            },
        ),
    ]
