# Generated by Django 3.0.8 on 2020-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0003_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Фирма'),
        ),
    ]
