# Generated by Django 3.0.8 on 2020-08-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0005_pc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pc',
            options={'verbose_name': 'Системный блок', 'verbose_name_plural': 'Системные блоки'},
        ),
        migrations.AddField(
            model_name='pc',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Имя компьютера'),
            preserve_default=False,
        ),
    ]
