# Generated by Django 3.0.8 on 2020-08-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0008_operationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='os',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arm.OperationSystem', verbose_name='Операционная система'),
            preserve_default=False,
        ),
    ]
