# Generated by Django 3.0.8 on 2020-08-28 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0009_pc_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='os',
        ),
    ]
