# Generated by Django 3.0.8 on 2020-08-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0011_auto_20200828_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNamber', models.CharField(max_length=50, verbose_name='Серийный номер')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('discription', models.TextField(blank=True, verbose_name='Описание')),
                ('catregory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.Category', verbose_name='Категория')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.Model', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя компьютера')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arm.PC', verbose_name='Системный блок')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
            },
        ),
    ]
