# Generated by Django 3.0.8 on 2020-08-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0012_arm_notebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arm',
        ),
    ]
