# Generated by Django 3.0.8 on 2020-08-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arm', '0013_delete_arm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='firm',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='catregory',
        ),
        migrations.RemoveField(
            model_name='notebook',
            name='model',
        ),
        migrations.DeleteModel(
            name='OperationSystem',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='catregory',
        ),
        migrations.RemoveField(
            model_name='pc',
            name='model',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Firm',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='NoteBook',
        ),
        migrations.DeleteModel(
            name='PC',
        ),
    ]
