# Generated by Django 3.0.8 on 2020-08-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20200829_1440'),
        ('catrige', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.Room', verbose_name='Место расположения'),
            preserve_default=False,
        ),
    ]
