# Generated by Django 3.0.8 on 2020-08-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=55, verbose_name='Отчество'),
        ),
    ]
