# Generated by Django 3.0.8 on 2020-08-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200819_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
