# Generated by Django 3.0.8 on 2020-08-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_uppdate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
