# Generated by Django 3.0.8 on 2020-08-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_date_uppdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_add',
        ),
    ]
