# Generated by Django 3.0.8 on 2020-08-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_remove_person_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_uppdate',
        ),
    ]
