# Generated by Django 3.0.8 on 2020-08-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Титул')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Zone', verbose_name='Зона')),
            ],
        ),
    ]
