# Generated by Django 3.0.8 on 2020-08-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_titul'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titul',
            options={'verbose_name': 'Титул', 'verbose_name_plural': 'Титулы'},
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кабинет')),
                ('titul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Titul', verbose_name='Титул')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
    ]
